### ISSUE TITLE
Not recognizing back quotes as quotes

### ISSUE THREAD

**Issue by montoya332** [KnisterPeter/react-to-typescript-definitions#1111]
Not sure if this is a bug or intended behavior but wanted to call out 

type: oneOf([`PRIMARY`, `SECONDARY`]), 
creates:          type?: any | any;

vs

type: oneOf(['PRIMARY', 'SECONDARY']),
create:         type?: "PRIMARY" | "SECONDARY";

**Comment by KnisterPeter** [comment]
@montoya332 Thats a missing feature. At creation time of the library, there where no template strings in the library.
If you need this, a PR is very welcome.
