### ISSUE TITLE
undefined prop name for nested props

### ISSUE THREAD

**Issue by dozortsev** [KnisterPeter/react-to-typescript-definitions#1131]
Hey

it seems that library doesn't pick name of prop if the prop is defined as string literal inside `.shape`

example:

```js
SomeComponent.propTypes = {
  action: PropTypes.shape({
    'aria-label': PropTypes.string,
```

it generated following types:

```typescript
export interface SomeComponentAction {
    undefined?: string;
```

could you please confirm that this is a bug? if so you could maybe point me out where the bug might be? I'm keen to fix this 🙂

thanks!

**Comment by KnisterPeter** [comment]
Hej @dozortsev,

this seems like a bug yes. Or more a missing property handling.
A good starting point to look into would be here:

https://github.com/KnisterPeter/react-to-typescript-definitions/blob/014f2b88999cf810d6b056bfb515d24af6b176dc/src/types.ts#L255-L263

**Comment by KnisterPeter** [comment]
Release as [3.0.1](https://github.com/KnisterPeter/react-to-typescript-definitions/releases/tag/v3.0.1)
