### ISSUE TITLE
Failed to lookup identifier for imported PropTypes

### ISSUE THREAD

**Issue by raDiesle** [KnisterPeter/react-to-typescript-definitions#1149]
Hey can this be handled, would be awesome!
Version using: 2.0.0, also reproduced on 3.0.1

Console output
/home/damend/IdeaProjects/react-ui/src/components/typography/severity-blocks/severity-text/severity-text.jsx Failed to lookup identifier
Line 7: SeverityText.propTypes = {
Line 8:   severity: PropTypes.oneOf(componentSeveritiesTypesConfig).isRequired,
Line 9:   text: PropTypes.string.isRequired,

File A:

import { componentSeveritiesTypesConfig } from 'components/configs/component-severities-types-config';
import React from 'react';
import * as PropTypes from 'prop-types';
import css from './severity-text.module.scss';

export const SeverityText = ({ severity, text }) => <span className={css[severity]}>{text}</span>;
SeverityText.propTypes = {
  severity: PropTypes.oneOf(componentSeveritiesTypesConfig).isRequired,
  text: PropTypes.string.isRequired,
};

File: component-severities-types-config

export const componentSeveritiesTypesConfig = ['', 'info', 'error', 'warn', 'success'];

**Comment by KnisterPeter** [comment]
Hi @raDiesle, I cannot see what exactly is wrong and where does it come from. A reproducable repository with a minimal example would be nice.
