### ISSUE TITLE
It should be possible to create typings for multiple components per input file.

### ISSUE THREAD

**Issue by ghost23** [KnisterPeter/react-to-typescript-definitions#151]
Currently, it seems, this tool only generates typings for the 'default' exported react component. For additional exported react components in the same file, no typings are generated.

**Comment by KnisterPeter** [comment]
I don't think so. As you can see in the [tests](https://github.com/KnisterPeter/react-to-typescript-definitions/blob/master/tests/es6-class.jsx) and the expected [results](https://github.com/KnisterPeter/react-to-typescript-definitions/blob/master/tests/es6-class.d.ts) non default exports are supported.

**Comment by ghost23** [comment]
The test you mention does not reflect my issue above. It only has one exported class. I mean something like this:

```
export const AdditionalComponent = () => <div>awesome</div>;

export default class MainComponent extends React.Component {
   ...
}
```

**Comment by KnisterPeter** [comment]
Then I misunderstood your issue request. Currently we are only able to recognize one react component per file. This is not about generating typings but about parsing the input files.
