### ISSUE TITLE
Stateless component

### ISSUE THREAD

**Issue by tomitrescak** [KnisterPeter/react-to-typescript-definitions#194]
Hi, do you plan to support stateless components as well? Thanks!

**Comment by KnisterPeter** [comment]
I think it could already work. Not completely sure, but give it a try. Otherwise, yes stateless components should be supported.
And as well contributions are welcome.

**Comment by tomitrescak** [comment]
Unfortunately it doesn't work;(

**Comment by KnisterPeter** [comment]
Released as 0.14.0
