### ISSUE TITLE
Feature request: create typings for other exports

### ISSUE THREAD

**Issue by unstubbable** [KnisterPeter/react-to-typescript-definitions#245]
It would be nice if other exports of a module (no React components) would also be added to the created interfaces.

**Comment by KnisterPeter** [comment]
The correct typings could only be guessed here, since JS does not have static analyzable types.
In most cases (besides const exports) this will lead to any, but the types would at least be declared.

**Comment by KingHenne** [comment]
That's better than nothing, I guess.
