### ISSUE TITLE
Nested complex types fall back to any

### ISSUE THREAD

**Issue by KingHenne** [KnisterPeter/react-to-typescript-definitions#246]
In our project some types fall back to `any` (error message: `Failed to infer PropType; Fallback to any`). It seems that nested complex types could be a cause of those issues, e.g.:

```
static propTypes = {
  foo: React.PropTypes.arrayOf(React.PropTypes.shape({
    bar: React.PropTypes.string,
    baz: React.PropTypes.string
  }))
}
```

**Comment by KnisterPeter** [comment]
@KingHenne is this still valid?

**Comment by KingHenne** [comment]
After the recent changes the listed issues are now mostly caused by references to imported objects. Thanks for the improved error messages!
