### ISSUE TITLE
Detect dynamic react components

### ISSUE THREAD

**Issue by FDiskas** [KnisterPeter/react-to-typescript-definitions#450]
Looks like syntax like this is not supported.

https://github.com/algolia/react-instantsearch/blob/746e362d936c5c0d5a79e2320e085b7b49855256/packages/react-instantsearch/src/core/createInstantSearch.js#L14-L35

**Comment by KnisterPeter** [comment]
It should be. There are plenty examples in the test folder. Please be a bit more specific about what is missing.

**Comment by FDiskas** [comment]
Please take a look here https://github.com/algolia/react-instantsearch/pull/701
The generated files are empty
1. Checkout branch 
2. Install dependencies
3. `npm run test:build`

**Comment by KnisterPeter** [comment]
Ah, I see. A class inside a function is not supported right now.
I'm not sure how hard it is to implement proper detection.
