### ISSUE TITLE
Stateless functional components

### ISSUE THREAD

**Issue by DeTeam** [KnisterPeter/react-to-typescript-definitions#480]
Right now we type stateless functional components as functions.
This means, that `children` are not included in the type definition by default.

We could do something like

```ts
export type Component = SFC<ComponentProps>;
```

What do you think?

**Comment by KingHenne** [comment]
Shouldn't the `children` be part of your `propTypes`?

**Comment by DeTeam** [comment]
Not sure.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L325 here `children` are assumed there by default.

Does the type change often? AFAIK people sometimes use children with a single function passed in, but in most of the cases `ReactNode` is fine.

**Comment by KingHenne** [comment]
In our code base `children` is always explicitly defined, sometimes as `PropTypes.string`, sometimes as `PropTypes.element` but in most cases it's either `PropTypes.node` or `PropTypes.node.isRequired`.

In any case, your suggestion could still make sense though.

**Comment by DeTeam** [comment]
@ingdir and I will submit a PR soon!

**Comment by KnisterPeter** [comment]
I think it is more correct to type SFC as SFC instead of as function.
I'll have a look at the PR.

**Comment by KnisterPeter** [comment]
Released in v0.28.1
