### ISSUE TITLE
Feature request: make babylon plugins configurable

### ISSUE THREAD

**Issue by muzea** [KnisterPeter/react-to-typescript-definitions#608]
https://github.com/KnisterPeter/react-to-typescript-definitions/blob/master/src/index.ts#L89

Sometimes our code will use another plugin, such as `exportDefaultFrom`. Modifying files one by one is a very painful thing.

**Comment by KnisterPeter** [comment]
Good point. Thanks for your idea.

**Comment by KnisterPeter** [comment]
Released in 1.2.0
