### ISSUE TITLE
Feature request: make eol configurable 

### ISSUE THREAD

**Issue by muzea** [KnisterPeter/react-to-typescript-definitions#609]
https://github.com/RyanCavanaugh/dts-dom/blob/master/lib/index.ts#L271

https://github.com/RyanCavanaugh/dts-dom/blob/master/lib/index.ts#L708

`dts-dom` uses `'\r\n'` to generate text by default. I hope this is configurable.

**Comment by KnisterPeter** [comment]
Thanks for your idea. I'll check that.

**Comment by KnisterPeter** [comment]
Released as v1.1.0

**Comment by muzea** [comment]
thx.
