### ISSUE TITLE
type definitions without module

### ISSUE THREAD

**Issue by artyomsv** [KnisterPeter/react-to-typescript-definitions#624]
Hi,

I have multiple Scenarios and not sure if your library support them:
- I would like to generate dts files for multiple JSX with single command
- I would like to generate index.d.ts file for each widget, but I do not want to declare module.

Do you have and examples how I can achieve this with react2dts?

Thanks in advance!

Artyom

**Comment by KnisterPeter** [comment]
Hi @artyomsv,
all current possible cases are in the various unit tests. Please have a look if there is something which fulfills your requirement. I'm not sure what you mean with `do not want to declare module`.

Right now it is only possible to create dts for one file at once. But it should be quite simple to eiter loop through them with a simple bash command or use the JS API.

**Comment by artyomsv** [comment]
@KnisterPeter  thanks for quick reply
Regarding declaring the module here is an example:
If I use your tool for JSX file I get something like this:

```ts
declare module 'name' {
    import * as React from 'react';

    export interface BaseInputCssModule {
       ...
    }

    export interface BaseInputProps {
        .......
    }

    const BaseInput: React.SFC<BaseInputProps>;

    export default BaseInput;

}
```
In my case I just want to place dts file together with my widget so I would expect to have index.d.ts file like:
```ts
export interface BaseInputCssModule {
  ...
}

export interface BaseInputProps {
  ...
}

declare const BaseInput: React.SFC<BaseInputProps>;

export default BaseInput;

```

**Comment by bartholomews** [comment]
Hello, I am having the same issue, `--top-level-module` seems to be ignored and it defaults same as I would do `react2dts --module-name moduleName`, is there something I am missing? Thanks

**Comment by KnisterPeter** [comment]
@bartholomews I have no clue. Can you please add your whole commandline you execute with all parameters and any output you get to this issue?

**Comment by bartholomews** [comment]
@sinnerschrader I think I have found the issue, it's defaulting only if the flag is set without value, if followed by any value it seems to work:

![react2dts-top-level-module-example](https://user-images.githubusercontent.com/8654136/57066080-865e5200-6ccb-11e9-8f09-f0daf8ed5051.png)

So it's not a big deal for us I think 👍

**Comment by KnisterPeter** [comment]
@bartholomews Intersting find. I'll flag this as bug as it should be fixed. But you already have your workaround. Thanks for sharing.

**Comment by jamesopti** [comment]
I ran into the same issue! Here was my workaround:

```sh
#
# Helper script to generate a master Typescript definition file.
#
INPUT_FILES=src/components/*/index.js
OUTPUT_FILE=types/index.d.ts
regex='src/components/([A-Za-z]+)/index.js'

# Initialize the output file with a header
cat > $OUTPUT_FILE <<- EOM
// Type definitions for <my project>
// Project: <my project>
// Definitions by:

/// <reference types="my-project" />

EOM

# Loop through all input files and run react2dts on them,
# concatenating the output to our single output file
for file in $INPUT_FILES; do
  [[ $file =~ $regex ]]
  comp_name=${BASH_REMATCH[1]}
  $(npm bin)/react2dts --file "$file" --name $comp_name >> $OUTPUT_FILE
done
```
