### ISSUE TITLE
Triple slash directive is broken #469

### ISSUE THREAD

**Issue by seawatts** [KnisterPeter/react-to-typescript-definitions#631]
I saw that #469 issue was resolved by #472 and then changed by #482 

For some reason I am now getting the error

```
[ts]
JSX element type 'MyComponent' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'MyComponent'.
[ts] JSX element class does not support attributes because it does not have a 'props' property.
```

The generated `.d.ts` file looks like the following:

```ts
declare module '@mycomponents/components' {
    import * as React from 'react';

    export interface MyComponentProps {
        children: React.ReactNode;
    }

    export default class MyComponent extends React.Component<MyComponentProps, any> {
        render(): JSX.Element;
    }
}

```

If I add
```
/// <reference types="react" />
```

Then this solves this issue.

**Comment by KnisterPeter** [comment]
@seawatts That looks a bit strange. The import should be sufficient. I'll have a look at this.

**Comment by seawatts** [comment]
@KingHenne any updates here?

**Comment by seawatts** [comment]
@KnisterPeter sorry to nag, but is there any update here?

**Comment by KnisterPeter** [comment]
@seawatts Sorry, haven't looked into it. I will do today.

**Comment by seawatts** [comment]
No big deal! Thanks for taking a look

**Comment by KnisterPeter** [comment]
@seawatts Can you please add an example of your component which is processed and leads to this error?

**Comment by seawatts** [comment]
Here is the component before it's been compiled 

```js
// theme.js
import React from "react"
import PropTypes from "prop-types"
import { Provider, Consumer } from "./context"

class Theme extends React.Component {
  static propTypes = {
    tokens: PropTypes.objectOf(PropTypes.string),
    children: PropTypes.element,
  }

  static defaultProps = { tokens: {} }

  render() {
    const { children, tokens } = this.props
    return (
      <Consumer>
        {contextTokens => (
          <Provider value={{ ...contextTokens, ...tokens }}>
            {children}
          </Provider>
        )}
      </Consumer>
    )
  }
}

export default Theme
```

Here is the output type file

```ts
import * as React from 'react';

export interface ThemeProps {
    tokens?: any;
    children?: React.ReactElement<any>;
}

export default class Theme extends React.Component<ThemeProps, any> {
    render(): JSX.Element;
}
```
Then when trying to consume this library, I get the following error:

```
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
```

```
Type '{ children: Element; tokens: any; }' is not assignable to type '{}'.
  Property 'tokens' does not exist on type '{}'.ts(2322)
```

Library versions:

Typescript: v3.2.1
react-to-typescript-definitions: v1.2.0
react: v16.6.3

**Comment by KnisterPeter** [comment]
Thanks, I'll look into it

**Comment by KingHenne** [comment]
@seawatts I can not reproduce your issue. Could you maybe look at [this repo](https://github.com/KingHenne/react2dts-issue-631) to see what is different there compared to your setup? Especially interesting would be how you try to import this component. Your latest comment suggests that this `Theme` component is published as a separate module (`@mycomponents/theme`). Is that correct?

@KnisterPeter Sorry, if you were already looking into it. I was just curious to look at this myself.

**Comment by seawatts** [comment]
@KingHenne yes the other `@mycomponents/theme` is coming in from another library. That library looks like what I get for the output.

**Comment by seawatts** [comment]
@KnisterPeter @KingHenne any updates here?

**Comment by KnisterPeter** [comment]
@seawatts Sorry, I haven't much time lately. Do you mind to create a minimal test case showing your problem. Ideally as a unit test and as PR here? It would be easier to fix then.
