### ISSUE TITLE
Return empty prop list when I try to use propTypes from other components

### ISSUE THREAD

**Issue by zmnv** [KnisterPeter/react-to-typescript-definitions#757]
Hello! For my design system I use third-part UI module for react-native.

I need to use propTypes from 'react-native-paper' in my components, so I just set propTypes = component.propTypes. But.

my Checkbox.jsx
![image](https://user-images.githubusercontent.com/25253501/59041106-2f3b3680-88a2-11e9-9fed-72f00e789c6c.png)

Source of CheckboxModule.Android prop types from 3rd party:

![image](https://user-images.githubusercontent.com/25253501/59041213-60b40200-88a2-11e9-8895-d64a0463693b.png)

Am I doing something wrong or `react-to-typescript-definitions` doesn't support that 'wired' magic like `my project -> module js component -> they .d.ts -> my component`?

Examples:

Js Checkbox Component from 3rd part:  
https://github.com/callstack/react-native-paper/blob/master/src/components/Checkbox.js

.d.ts file:
https://github.com/callstack/react-native-paper/blob/master/typings/components/Checkbox.d.ts

**Comment by KnisterPeter** [comment]
@zmnv Hi, sorry for my late response.
I don't get the point of your request I think. You linked to typescript definitions (Checkbox.d.ts) so you don't need `react-to-typescript-definitions` I guess.
This library is about converting proptypes to typescript '.d.ts'-Files. What did I miss here?

**Comment by zmnv** [comment]
@KnisterPeter 

Hello! Okay, lets more information:

1. I use react native by .js / .jsx
2. Also I use third party module (react-native-paper is just for example)
3. That module has structure – component = JSX components + .d.ts definitions.
4. I create my component also = JSX + .d.ts.
5. In propTypes of .jsx fine i define some:
```
Component.propTypes = ThirdPartyModule.propTypes
```
or
```
Component.propTypes = {
    myProp: ....,
    ...ThirdPartyModule.propTypes
}
```
6. I also use that construction between my components like:
```
MyComponentContainer.propTypes = MyComponent.propTypes
```

7. I try to generate `.d.ts` file and it returns nothing.

8 Also generator returns nothing when:
```
export default React.forwardRef((props, ref) => <Component {...props} forwardedRef={ref} />);
```

My question is:
1. How to automate props interfaces generation in that case – when I use `propTypes = propTypes`? It returns nothing.
2. How can I take third-party-module .d.ts files and pass it in generator? 

You can look at my video (google drive, 0:52 secs) how I use your generator.:
https://drive.google.com/file/d/1tRwDEAMP2BCySOl6E6SJyHQPZXI0FF2Z/view?usp=sharing

So, how to automate using of third-party-modules definition in my components to generate right code and not to rewrite generated result?

**Comment by KnisterPeter** [comment]
Now I think I see your case.

This type of definition `Component.propTypes = ThirdPartyModule.propTypes` is not supported. And it would probably be supported in the future, if no one is willing to implement it. Its a large effort with lot of edge cases.

Since there are already type definitions, it would be better to just use these or adopt them to your need.

**Comment by zmnv** [comment]
@KnisterPeter got you! So.. Anyway.. Thank you!)

I can give you present. If anybody needs your generator on MacOS, they can:

1. Create app from Automator to generate type definitions
2. Apple Script:
```
on run {input, parameters}
	
	tell application "Terminal"
		activate
		do script "cat " & (input as string) & " | react2dts --top-level-module"
	end tell
	
end run
```
3. Before script you can define `Input` as:
![image](https://user-images.githubusercontent.com/25253501/59832576-6b749980-936e-11e9-8dfd-79b22d538b2f.png)

![image](https://user-images.githubusercontent.com/25253501/59832629-8c3cef00-936e-11e9-8a70-4bda6917cbcf.png)

[Generate Type.app.zip](https://github.com/KnisterPeter/react-to-typescript-definitions/files/3309442/Generate.Type.app.zip)
