### ISSUE TITLE
Generating a single type definition file for non-Typescript components

### ISSUE THREAD

**Issue by jamesopti** [KnisterPeter/react-to-typescript-definitions#836]
I have a library of react components which are all written in plain JS using the `PropTypes` library.

I'd like to use this tool to generate a single typescript definition file so consumers of my library can have types.

My work in progress so far looks like this script, but I'm having trouble importing it in my repo.

Am I on the right path? Does my root file need to be wrapped in a declaration?

```sh
#
# Helper script to generate a master Typescript definition file.
#
INPUT_FILES=src/components/*/index.js
OUTPUT_FILE=types/index.d.ts
regex='src/components/([A-Za-z]+)/index.js'

# Initialize the output file with a header
cat > $OUTPUT_FILE <<- EOM
// Type definitions for <my project>
// Project: <my project>
// Definitions by:

/// <reference types="my-project" />

EOM

# Loop through all input files and run react2dts on them,
# concatenating the output to our single output file
for file in $INPUT_FILES; do
  [[ $file =~ $regex ]]
  comp_name=${BASH_REMATCH[1]}
  $(npm bin)/react2dts --file "$file" --name $comp_name >> $OUTPUT_FILE
done
```

**Comment by KnisterPeter** [comment]
Hi @jamesopti,
from what I can say is that it looks right. But it highly depends on how you want to import your component types (and components).
Do you want a declaration file next to your sources and some kind-of-'global' types? Or do you want to have it like the types are from an `@types` folder?
The structure need to be different then.
