### ISSUE TITLE
Jsdoc is not generated

### ISSUE THREAD

**Issue by raDiesle** [KnisterPeter/react-to-typescript-definitions#981]
First of all great tool and we do use it with pleasure every day!

Used version: 2.0.0

applying generateFromFile(null, filePath, { babylonPlugins: ['optionalChaining'] })

on (breaking the markdown formatting)

`/**
 * A component to setup
 * @param {String} basename - base url for react 
 * @param {String} baseUrl - base url for API
 * @param {Object} translations - {en: JSON, de: JSON} json translation English and German languages
 * @param {Node} children - content to render inside the component(should not be passed as a prop)
 * @param {String} homeUrl - url to home page of application, used to redirect from Error page, etc.
 * @param {String} errorPagePath - path to error page within your React application
 * @param {Function} getPlatformContextData
 *  */
export function MyComp({
...
}
MyComp.defaultProps = {
  forceSentryIoToEnable: false,
};

MyComp.propTypes = {
  children: PropTypes.node.isRequired,
  basename: PropTypes.string.isRequired,
  baseUrl: PropTypes.string.isRequired,
  homeUrl: PropTypes.string.isRequired,
  errorPagePath: PropTypes.string.isRequired,
  getPlatformContextData: PropTypes.func.isRequired,
  // eslint-disable-next-line react/forbid-prop-types
  translations: PropTypes.object.isRequired,
  forceSentryIoToEnable: PropTypes.bool,
};`

Does not preserve the code comments, but generates

`
import * as React from 'react';

export interface MyComp{
    children: React.ReactNode;
    basename: string;
    baseUrl: string;
    homeUrl: string;
    errorPagePath: string;
    getPlatformContextData: (...args: any[])=>any;
    translations: Object;
    forceSentryIoToEnable?: boolean;
}

export const MyComp: React.FC<MyCompProps>;`

Any idea? I do not see there is a test for JSdoc, yet in the project.

**Comment by KnisterPeter** [comment]
Hi @raDiesle, I think this is a missing feature.
If possible please provide a PR with this :smiley:

**Comment by raDiesle** [comment]
Hi @KnisterPeter , I see there is some code to handle documentation, so is there any way to already have comments provided, just I use it in a non supported way? Will it work with inline jsdoc or to provide it for PropTypes?

**Comment by KnisterPeter** [comment]
@raDiesle I initially thought that it is already supported. Not sure where we throw away/not copy over the comments.
